### ISSUE TITLE
jvm error

### ISSUE THREAD

**Issue by DexrnZacAttack** [vlOd2/TooGood4U#4]
maybe i am dumb but i get error

`Error: A JNI error has occured, please check your installation and try again`

I did reinstall Java 17 with no fix.

**Comment by vlOd2** [comment]
Run from a shell (Command Prompt, powershell) with `java -jar <jar file>` where `<jar file>` is the name of the jar, should be `TooGood4U.jar` but in-case you changed it
Also make sure you are in the same directory as the jar file

**Comment by DexrnZacAttack** [comment]
am dumb and it used java8 as default
